apiVersion: v2
name: voterr
description: Movie night voting app with Plex integration
type: application
version: 0.1.0
appVersion: "1.0.1"
keywords:
  - plex
  - movie
  - voting
  - radarr
  - tautulli
home: https://github.com/Tmirage/voterr
sources:
  - https://github.com/Tmirage/voterr
maintainers:
  - name: Tmirage
